resolver: lts-14.20
packages:
- ./backend
- ./frontend
- ./common
- ./reflex-dom-bulma
extra-deps:
- reflex-0.6.3
- reflex-dom-0.5.3
- reflex-dom-core-0.5.3
- ghcjs-dom-0.9.4.0
- ghcjs-dom-jsaddle-0.9.4.0
- jsaddle-0.9.7.0
- jsaddle-dom-0.9.4.0
- bimap-0.3.3
- dependent-map-0.3
- dependent-sum-0.6.2.0
- dependent-sum-template-0.1.0.0
- constraints-extras-0.3.0.2
- ref-tf-0.4.0.2
- monoidal-containers-0.6.0.1
- witherable-0.3.1
- zenc-0.1.1
- polysemy-1.2.3.0
- git: https://github.com/isumif/servant-reflex.git
  commit: 0f29197c52b82418685765d61c784da9422dbbad
- git: https://github.com/reflex-frp/reflex-dom-contrib.git
  commit: b9e2965dff062a4e13140f66d487362a34fe58b3
- git: https://github.com/IsumiF/jsaddle-warp
  commit: 6b4ccbdb330b56bb2171c665e02bef388df458bb
# - smtp-mail-0.2.0.0
- HaskellNet-SSL-0.3.4.1
- HaskellNet-0.5.1
flags:
  reflex-dom:
    use-warp: true
allow-newer: true