name: croe-backend
version: 0.1.0.0
license: BSD3
author: "fengzelin.isumi"
maintainer: "fengzelin.isumi@bytedance.com"
copyright: "2019 fengzelin.isumi"
synopsis: croe backend
category: Web
description: Please see the README on GitLab at <https://code.byted.org/fengzelin.isumi/weekly-report/blob/master/README.md>

ghc-options: -Wall -fplugin=Polysemy.Plugin
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeOperators
  - KindSignatures

dependencies:
  - base >= 4.7 && < 5
  - freer-simple
  - polysemy
  - polysemy-plugin

library:
  source-dirs: src
  dependencies:
    - HaskellNet-SSL
    - MonadRandom
    - aeson
    - bytestring
    - cache
    - clock
    - containers
    - croe-common
    - cryptonite
    - fast-logger
    - file-embed
    - hashable
    - http-client
    - http-client-tls
    - http-types
    - lens
    - monad-control
    - monad-logger
    - mtl
    - optparse-applicative
    - pandoc
    - pandoc-types
    - persistent
    - persistent-mysql
    - persistent-template
    - random
    - resource-pool
    - servant
    - servant-client
    - servant-server
    - string-interpolate
    - text
    - time
    - transformers
    - transformers-base
    - unliftio-core
    - unordered-containers
    - wai-cors
    - warp
    - warp-tls

executables:
  croe-backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - croe-backend

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools: hspec-discover:hspec-discover
    dependencies:
      - croe-backend
      - hspec
      - QuickCheck
  int:
    main: Spec.hs
    source-dirs: test/int
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools: hspec-discover:hspec-discover
    dependencies:
      - croe-backend
      - QuickCheck
      - croe-common
      - hspec
      - http-client
      - lens
      - port-utils
      - servant
      - servant-client
      - text
      - http-types
