name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v6
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.6.5"
          cabal-version: "3.0"
      - name: Checkout submodules
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
      - uses: actions/cache@v1
        name: Cache Stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack
      - name: Install Tools
        run: |
          sudo npm i -g sass
          sudo npm i -g google-closure-compiler
          sudo apt-get install -y libmysqlclient-dev
      - name: Decrypt Secret
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output backend/config/ci.json backend/config/ci.json.gpg
      - name: Build
        run: make build
