name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v6
      - name: Nix use reflex cache
        run: |
          echo "binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org" | sudo tee -a /etc/nix/nix.conf
          echo "binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=" | sudo tee -a /etc/nix/nix.conf
          echo "binary-caches-parallel-connections = 40" | sudo tee -a /etc/nix/nix.conf
          echo "sandbox = true" | sudo tee -a /etc/nix/nix.conf
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.6.5"
          cabal-version: "3.0"
      - name: Checkout submodules
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
      - uses: actions/cache@v1
        name: Cache Stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack
      - name: Install Tools
        run: |
          sudo npm i -g sass
          sudo npm i -g google-closure-compiler
          sudo apt-get update -y
          sudo apt-get install -y libmysqlclient-dev
      - name: Decrypt Secret
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEY" --output backend/config/test.json backend/config/test.json.gpg
      - name: Build Frontend
        run: make frontend
      - name: Build Backend
        run: make backend
      - name: Run Tests
        run: |
          sudo mkdir -p /var/croe
          sudo chown -R $USER /var/croe
          make test
