name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v6
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.6.5"
          cabal-version: "3.0"
      - name: Checkout submodules using a PAT
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
      - name: Install Tools
        run: |
          sudo npm i -g sass
          sudo npm i -g google-closure-compiler
      - name: Build
        run: make build
