name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install Tools
      run: |
        sudo npm i -g sass
        sudo npm i -g google-closure-compiler
    - name: Build
      run: make build
